# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookApp', '0002_auto_20171030_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('date_of_registration',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_registration',
            field=models.DateField(db_index=True, verbose_name='Дата регистрации'),
        ),
    ]
